# AUTOGENERATED FILE! PLEASE DON'T EDIT HERE. EDIT THE SOURCE NOTEBOOKS INSTEAD
"""
This is for all short and random quality-of-life utilities."""
import k1lib as k1; import k1lib.cli as cli
from k1lib.web.init import *
bcrypt = k1.dep("bcrypt")
__all__ = ["table", "hashPw", "checkPw", "new", "get", "login"]
_table = [None]
def table():                                                                     # table
    if _table[0] is None:                                                        # table
        s = db(); s.query("CREATE TABLE IF NOT EXISTS users ( id       INTEGER primary key autoincrement, name     TEXT, username TEXT, password TEXT );") # table
        s.query("CREATE INDEX IF NOT EXISTS users_username ON users (username);"); _table[0] = s["users"] # table
    return _table[0]                                                             # table
def hashPw(pw:str) -> str: return bcrypt.hashpw(pw.encode(), bcrypt.gensalt()).decode() # hashPw
def checkPw(pw:str, hashedPw:str) -> bool: return bcrypt.checkpw(pw.encode(), hashedPw.encode()) # checkPw
def new(username:str, password:str):                                             # new
    if table().lookup(username=username) is not None: raise FailureException(f"Username '{username}' already exists") # new
    table().insert(username=username, password=password)                         # new
def get(idx:int): return table()[idx]                                            # get
def login(username:str, password:str) -> "User|None":                            # login
    user = table().lookup(username=username)                                     # login
    if user: return user if checkPw(password, user.password) else None           # login
    else: return table().insert(username=username, password=hashPw(password))    # login
